# obtener todos los usuarios
GET http://localhost:3000/users

###

#obtener usuario por id
GET http://localhost:3000/users/1

###

#crear usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Eduardo" ,
  "lastname": "Villegas",
  "mail": "eduardo@mail.com",
  "active": true,
  "role": "admin"
}


###

#crear usuario con un dato faltante
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Eduardo" ,
  "lastname": "Villegas",
  "active": true,
  "role": "admin"
}


###

#crear usuario con 2 datos faltantes
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Eduardo" ,
  "active": true,
  "role": "admin"
}

###

#elimninar usuario por id
DELETE http://localhost:3000/users/6